language: ruby
sudo: false
rvm:
  - '2.2.3'
services:
  - mysql
script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec